### ISSUE TITLE
Incorrect LibriVox Labelling

### ISSUE THREAD

**Issue by ee-tester** [microsoft/DNS-Challenge#51] opened 2021-07-01 01:19 UTC
The data in the `read_speech` directory appears to reference the book, chapter, and speaker from the LibriVox database associated with the wav file. This metadata does not appear to be correct. For example, the file:

```
book_00082_chp_0011_reader_01593_0.wav
```
is not from [reader 01593](https://librivox.org/reader/1593) but instead from [reader 11223](https://librivox.org/reader/11223). This is just one example, this seems to happen for many, many files.

I'm wondering if this is a known issue and if there is any mapping from the DNS based labelling to the actual LibriVox data.

**Comment by motus** [comment] 2021-11-11 03:57
@ee-tester Thanks for the heads up. I'll check if the issue is with the original LibriVox data and let you know. Either way, we'll probably keep the data as is for now. We'll need to fix it when we do personalized DNS, though. Stay tuned!

**Comment by motus** [comment] 2021-11-11 18:42
@hdubey and I (@motus) will take a close look. If that's a LibriVox issue, it is a big problem for personalized DNS

**Comment by hdubey** [comment] 2022-01-11 23:02
Closing as OP did not share his approach for finding the discrepancy in speaker ID.

**Closed by hdubey** 2022-01-11 23:02 UTC
Labels: bug, question
